---
# This Role sets a machine up for basic development tasks

- name: Install Role Packages
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items: role_pkgs

- name: Clone Dotfile Repo
  git: repo=https://github.com/csrhau/dotfiles.git
       dest=dotfiles

- name: Setup Dotfiles
  command: make
  args:
    chdir: dotfiles
