role_pkgs:
- libssl-dev
- zlib1g-dev
- libbz2-dev
- libreadline-dev
- libsqlite3-dev
- wget
- curl
- llvm
- libncurses5-dev

pyenv_plugins:
- name: pyenv-update
  repo: https://github.com/yyuu/pyenv-update.git
