---
# This Role sets a machine up for basic usage
# by installing general packages (vim, curl etc)

- name: Install Role Packages
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items: role_pkgs
