---
# This Playbook Configures The Development Box


- hosts: all
  become: yes
  roles:
  - sane_environment # Installs basic prerequisite packages (build-essential..)
  - environment_modules
  - pyenv
  - golang_module

- hosts: all
  roles: 
  - development_setup
