---
# This Playbook Configures The Development Box


- hosts: all
  become: yes
  roles:
  - sane_environment # Installs basic prerequisite packages (build-essential..)
  - swapfile
  - environment_modules
  - golang_module
  - nodejs_module
  - phantomjs_module

- hosts: all
  roles: 
  - pyenv
  - rbenv
  - development_setup
