---
# This role sets up rbenv for a node
- name: Install Role Packages
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items: role_pkgs

- name: Check Out Latest rbenv
  git: repo=https://github.com/sstephenson/rbenv.git
       dest=.rbenv

- name: Check out rbenv plugins
  git: repo={{ item.repo }}
       dest=.rbenv/plugins/{{ item.name }}
  with_items: rbenv_plugins

- name: Include rbenv in path
  lineinfile: line='export PATH="$HOME/.rbenv/bin:$PATH"' 
              dest=.bashrc
  
- name: Include rbenv setup source script
  lineinfile: line='eval "$(rbenv init -)"' 
              dest=.bashrc
